//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp.General.DataAccess.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ErpDBEntities : DbContext
    {
        public ErpDBEntities()
            : base("name=ErpDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Currencys> Currencys { get; set; }
        public virtual DbSet<DocumentTypes> DocumentTypes { get; set; }
        public virtual DbSet<MovementsAccountsReceivable> MovementsAccountsReceivable { get; set; }
        public virtual DbSet<MovementsDebtsToPay> MovementsDebtsToPay { get; set; }
        public virtual DbSet<MovementsInventory> MovementsInventory { get; set; }
        public virtual DbSet<Parameters> Parameters { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<PersonType> PersonType { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<TipoCambio> TipoCambio { get; set; }
        public virtual DbSet<RolUsers> RolUsers { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
