//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp.General.DataAccess.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementsInventory
    {
        public int CompanyId { get; set; }
        public long InventoryMovementId { get; set; }
        public short DocumentTypeId { get; set; }
        public long ProductId { get; set; }
        public decimal Quantity { get; set; }
        public System.DateTime MovementDate { get; set; }
        public System.DateTime MovementLogDate { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal UnitCost { get; set; }
        public Nullable<short> CostCurrencyId { get; set; }
        public Nullable<short> UnitPriceCurrencyId { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Currencys Currencys { get; set; }
        public virtual Currencys Currencys1 { get; set; }
        public virtual DocumentTypes DocumentTypes { get; set; }
        public virtual Products Products { get; set; }
    }
}
