//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp.General.DataAccess.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameters
    {
        public int CompanyId { get; set; }
        public int ParameterId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string Details { get; set; }
    
        public virtual Companies Companies { get; set; }
    }
}
