//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp.General.DataAccess.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCambio
    {
        public long Consecutivo { get; set; }
        public int Cod_IndicadorInterno { get; set; }
        public System.DateTime Des_Fecha { get; set; }
        public decimal Num_Valor { get; set; }
    }
}
